name: Build and Test
on:
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*

jobs:
  build_test:
    name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: 
          - 11
          - 12
          - 14
        os: 
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm run build
          npm run test