name: Publish, Coverage and Document

on:
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm run build
          npm run test

  coverage:
    needs: build_test
    name: Run coverage on Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install codecov
        run: |
          npm install -g codecov
          npm install
          npm run coverage

  docs:
    needs: build_test
    name: Builds the Documentation from TypeDoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Compile Documentation
        run: |
          npm install
          npm run docs

  publish_npm:
    needs: [build_test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with: 
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Update package version
        run: |
          npm run semantic-release
          npm publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_github:
    needs: [build_test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: Update package version
        run: |
          git config user.name "Spencer Pollock"
          git config user.email "spencer@spollock.ca"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}