name: Publish, Coverage and Document

on:
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build and test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          yarn install
          yarn build
          yarn test

  coverage:
    needs: build_test
    name: Run coverage on Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install codecov
        run: |
          yarn global add codecov
          yarn
          yarn coverage

  docs:
    needs: build_test
    name: Builds the Documentation from TypeDoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Compile Documentation
        run: |
          yarn
          yarn docs

  publish_npm:
    needs: [build_test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with: 
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Update package version
        run: |
          yarn semantic-release
          yarn publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_github:
    needs: [build_test, coverage, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: '@contesini'
      - name: Update package version
        run: |
          git config user.name "contesini"
          git config user.email "allancontesini@gmail.com"
      - run: |
          yarn install --frozen-lockfile
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHUB_TOKEN }}